<?xml version="1.0"?>
<model:physical name="pioneer2dx"
  xmlns:model="http://playerstage.sourceforge.net/gazebo/xmlschema/#model"
  xmlns:sensor="http://playerstage.sourceforge.net/gazebo/xmlschema/#sensor"
  xmlns:body="http://playerstage.sourceforge.net/gazebo/xmlschema/#body"
  xmlns:geom="http://playerstage.sourceforge.net/gazebo/xmlschema/#geom"
  xmlns:joint="http://playerstage.sourceforge.net/gazebo/xmlschema/#joint"
  xmlns:controller="http://playerstage.sourceforge.net/gazebo/xmlschema/#joint"
  xmlns:interface="http://playerstage.sourceforge.net/gazebo/xmlschema/#joint"
  xmlns:xacro="http://ros.org/wiki/xacro"
  >


  <!-- ============================ -->
  <!-- BEGIN XACRO DEFINITIONS      -->
  <!-- ============================ -->

  <!-- Height to elevate all parts to avoid collision with the ground-->
  <xacro:property name="HEIGHT" value="0.15"/>

  <!-- Macro to create a wheel -->
  <xacro:macro name="WHEEL" params="name parent reflect">

    <!-- Wheel body -->
    <body:cylinder name="${name}_wheel">
      <xyz>0.1 ${-reflect*0.17} ${-0.0725 + HEIGHT}</xyz>
      <rpy>0 90 90</rpy>
      <geom:cylinder name="${name}_wheel_geom">
        <size>0.075 0.05</size>
        <mass>0.5</mass>
        <visual>
          <rpy>-90 0 0</rpy>
          <size>0.15 0.05 0.15</size>
          <mesh>Pioneer2dx/tire.mesh</mesh>
          <material>Gazebo/Black</material>
        </visual>
        <visual>
          <rpy>-90 0 0</rpy>
          <size>0.088 0.05 0.088</size>
          <mesh>Pioneer2at/wheel.mesh</mesh>
          <material>Gazebo/Gold</material>
        </visual>
        <visual>
          <rpy>0 0 0</rpy>
          <xyz>0 0 ${reflect*0.015}</xyz>
          <size>0.04 0.04 0.08</size>
          <mesh>unit_cylinder</mesh>
          <material>Gazebo/Black</material>
        </visual>
      </geom:cylinder>
    </body:cylinder>

    <!-- Join wheel and base_link -->
    <joint:hinge name="${name}_wheel_joint">
      <body1>${name}_wheel</body1>
      <body2>base_link</body2>
      <anchor>${name}_wheel</anchor>
      <anchorOffset>0 0 ${reflect*0.04}</anchorOffset>
      <axis>0 1 0</axis>
      <erp>0.8</erp>
      <cfm>10e-5</cfm>
    </joint:hinge>

  </xacro:macro>

  <!-- ============================ -->
  <!-- END XACRO DEFINITIONS        -->
  <!-- ============================ -->


  <xyz>0.0 0.0 0.0</xyz>
  <rpy>0.0 0.0 0.0</rpy>
  <canonicalBody>base_link</canonicalBody>

  <!-- Base link -->
  <body:box name="base_link">
    <xyz>0.0 0.0 ${0.0 + HEIGHT}</xyz>
    <rpy>0.0 0.0 0.0</rpy>
    <geom:box name="base_link_geom">
      <xyz>0 0 0.0</xyz>
      <size>0.445 0.277 0.17</size>
      <mass>2.0</mass>
      <mu1>1</mu1>
      <visual>
        <size>0.5 0.277 0.17</size>
        <xyz>0 0 0.04</xyz>
        <rpy>0 180 0</rpy>
        <mesh>Pioneer2dx/chassis.mesh</mesh>
        <material>Gazebo/Pioneer2Body</material>
      </visual>
      <visual>
        <xyz>0.015 0 0.0975</xyz>
        <rpy>0 0 0</rpy>
        <mesh>Pioneer2at/chassis_top.mesh</mesh>
        <material>Gazebo/Black</material>
      </visual>
      <visual>
        <xyz>0.21 0.0 0.068</xyz>
        <rpy>0 0 0</rpy>
        <size>0.12 0.29 0.034</size>
        <mesh>Pioneer2at/sonarbank.mesh</mesh>
        <material>Gazebo/Gold</material>
      </visual>
      <visual>
        <xyz>-0.178 0.0 0.068</xyz>
        <rpy>0 0 180</rpy>
        <size>0.12 0.29 0.034</size>
        <mesh>Pioneer2at/sonarbank.mesh</mesh>
        <material>Gazebo/Gold</material>
      </visual>
    </geom:box>
  </body:box>

  <!-- Castor -->
  <body:sphere name="castor">
    <xyz>-0.200 0 ${-0.108 + HEIGHT}</xyz>
    <rpy>0 0 0</rpy>
    <geom:sphere name="castor_geom">
      <size>0.04</size>
      <mass>0.5</mass>
      <visual>
        <scale>0.04 0.04 0.04</scale>
        <mesh>unit_sphere</mesh>
        <material>Gazebo/Black</material>
      </visual>
    </geom:sphere>
  </body:sphere>

  <!-- Join castor and base_link -->
  <joint:ball name="castor_joint">
    <body1>castor</body1>
    <body2>base_link</body2>
    <anchor>castor</anchor>
    <erp>0.8</erp>
    <cfm>10e-5</cfm>
  </joint:ball>

  <!-- Wheels -->
  <xacro:WHEEL name="left" parent="base_link" reflect="1"/>
  <xacro:WHEEL name="right" parent="base_link" reflect="-1"/>

  <!-- Controller -->
  <controller:differential_position2d name="controller1">
    <update>100</update>
    <leftJoint>left_wheel_joint</leftJoint>
    <rightJoint>right_wheel_joint</rightJoint>
    <wheelSeparation>0.34</wheelSeparation>
    <wheelDiameter>0.15</wheelDiameter>
    <torque>5</torque>
    <interface:position name="position_iface_0"/>
  </controller:differential_position2d>

</model:physical>
